services:
  db:
    image: mysql:latest
    command: --explicit_defaults_for_timestamp=1 --tls-version=TLSv1.2 --pid-file=/var/run/mysqld/mysqld.pid
    volumes:
      - db-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
volumes:
  db-data:
